### ISSUE TITLE
When demo.py is run according to the readme content, the final data is all 0. Why is this?

### ISSUE THREAD

**Issue by Hwwg** [q-rz/enamel#1]
<img width="1791" alt="image" src="https://github.com/user-attachments/assets/c06ba111-bbb9-41b7-bc8e-8676fb8548b4">

**Comment by q-rz** [comment]
Thank you for your valuable feedback!

This is possibly a compatibility issue about the environment. Would you mind sharing more information about this issue? This can help us improve the code/documentation. Thanks!

**Comment by Hwwg** [comment]
I am running on the macos platform and this is my debugging result:
Evaluation #1: 1% | | 1/142 [00:00<01:33, 1.51it/s] System maximum memory limit: 9223372036854775807 bytes
Current RLIMIT_DATA: (9223372036854775807, 9223372036854775807)
Set memory limit to: 68719548 bytes
Exception occurred: Current limit exceeds maximum limit
System maximum memory limit: 9223372036854775807 bytes
Current RLIMIT_DATA: (9223372036854775807, 9223372036854775807)
Set memory limit to: 68719548 bytes
Exception occurred: Current limit exceeds maximum limit
May I ask what platform you are using?

**Comment by q-rz** [comment]
The zero scores are possibly because an error occurred during evaluation. If an error occurs during evaluation, our evaluator function will catch the error and assign a zero score to the code sample. Could you find out what error occurred in your evaluation?

My platform is Ubuntu 20.04.6 LTS. Our `set_memory_limit` function was tested only under Linux systems, but Mac OS is not a Linux system but a Unix system. This may have caused an error. 

By the way, the memory limit (68719548 B=65.5MB) might be a bit too small, which can also negatively affect the evaluation results. Since we have large-scale test cases, the recommended memory limit is 4GB.
